### PR TITLE
[Merged by Bors] - RBAC Setup for Spark Driver

### LINKED ISSUE #29: k8s Role setup + Helm
We want an s3 section in the CRD, for now we can use the same structure as in druid:

    s3:
      endpoint: s3-de-central.profitbricks.com
      credentialsSecret: s3-credentials

for the endpoint there is a configoption, the access key and secret key should be mounted from the referenced secret. The secret structure used in druid is:
    
    apiVersion: v1
    kind: Secret
    metadata:
      name: s3-credentials
    stringData:
      accessKeyId: YOURACCESSKEYIDHERE
      secretAccessKey: YOURSECRETACCESSKEYHERE

The secret should be mounted and the env vars for that are `AWS_ACCESS_KEY_ID` `AWS_SECRET_ACCESS_KEY`. The secret also needs to be mounted in the executors, so they can read from S3 too; so the pod template needs to be adjusted accordingly.
      
---
Update:

We don't know in which namespaces the `SparkApplication`s will be created, so we will need to create the `ServiceAccount` and `RoleBinding` on demand in the namespace of the `SparkApplication`. Our Kafka Operator is already creating service accounts, we can have a look there.

The role can be a `ClusterRole`, created in the Helm Chart.

### PR DESCRIPTION
**Pull request by fhennig**
## Description

- Adds a new ClusterRole to the Helm Chart that is used by spark-submit and the driver pod to manage pods & services.
- Adds code that generates a `ServiceAccount` and `RoleBinding` to the role for every `SparkApplication`. The account is deleted once the application is deleted.

fixes #29 

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by adwk67** [comment]
Tested examples with externally-running operator (+ manually applied clusterrole) and also with helm chart.
LGTM.

**Comment by fhennig** [comment]
bors merge

**Review by adwk67 — APPROVED** [review]
Approved.

**Comment by fhennig** [comment]
bors merge

**Pull request closed without merging**
