### PR TITLE
[Merged by Bors] - Support specifying Service type

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

For https://github.com/stackabletech/issues/issues/360

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
Started https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/spark-k8s-operator-it-custom/82/

**Review by maltesander — APPROVED** [review]
LGTM overall. Lets wait for @razvan review before merging.

**Review by razvan — COMMENTED** [review]
The history test fails on OpenShift.

**Comment by sbernauer** [comment]
I would have though that this PR does not cause this failure, but who knows? ;)
Do you have any error message or a cluster I can connect to to debug the problem?

**Comment by razvan** [comment]
Works now. The problem seems to have been a "broken" installation of the secret-operator. After reinstalling it, it worked.

**Review by razvan — APPROVED** [review]

**Comment by sbernauer** [comment]
Alright thx! kuttl tests on jenkins passed as well

**Pull request closed without merging**
