### PR TITLE
[Merged by Bors] - fix: Typo in executor cpu limit property

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Introduced in https://github.com/stackabletech/spark-k8s-operator/pull/256

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
Thanks. LGTM if integration and getting started tests pass!
Edit: Maybe add changelog entry?

**Comment by sbernauer** [comment]
Started https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/spark-k8s-operator-it-custom/93/

**Comment by sbernauer** [comment]
bors r+
tests passed

**Comment by lfrancke** [comment]
Same question: This made it into 23.7?

**Comment by maltesander** [comment]
Yes this was a bug an was cherry picked into 23.7 branch (other releases were not affected).

**Pull request closed without merging**
